<a href="https://colab.research.google.com/github/chandraSekar123/ML_Deployment_Django/blob/master/Tensorflow_and_Keras_model_build_early_stop_saving_loading_dump_weight_extrac_check.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: using Google CoLab


In [4]:
import tensorflow as tf
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 2.2.0-rc3


In [30]:
import tensorflow as tf

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

print("shape of marix 1  is",matrix2.get_shape)
print("shape of marix  2 is",matrix2.get_shape)
print(product)

print(float(product))

shape of marix 1  is <bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [2.]], dtype=float32)>>
shape of marix  2 is <bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [2.]], dtype=float32)>>
tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
12.0


In [22]:
# Enter an interactive TensorFlow Session.
import tensorflow as tf

x = tf.Variable([1.0, 2.0])
a = tf.constant([3.0, 3.0])

# Add an op to subtract 'a' from 'x'.  Run it and print the result
sub = tf.subtract(x, a)
print(sub)
print(sub.numpy())
y=sub.numpy()

tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
[-2. -1.]


In [27]:
x.assign([4.0, 6.0])
print(sub)
print(sub.numpy())

tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
[-2. -1.]


In [28]:
Introduction to Keras
Keras is a layer on top of Tensorflow that makes it much easier to create neural networks. Rather than define the graphs, like you see above, you define the individual layers of the network with a much more high level API. Unless you are performing research into entirely new structures of deep neural networks it is unlikely that you need to program TensorFlow directly.

SyntaxError: ignored

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression



In [50]:
# Build the neural network
n_features=x.shape[1]
nhidden1=25 
nhidden2=10
nhidden3=1
act1='relu'
act2='relu'
mymodel=Sequential()
mymodel.add(Dense(units=nhidden1,input_dim=n_features,activation=act1))
mymodel.add(Dense(units=nhidden2,activation=act2))
mymodel.add(Dense(units=nhidden3))
mymodel.compile(loss='mean_squared_error', optimizer='adam')
mymodel.fit(x,y,verbose=1,epochs=100)

Epoch 1/100
13/13 [==============================] - 0s 2ms/step - loss: 103342.0469
Epoch 2/100
13/13 [==============================] - 0s 1ms/step - loss: 17396.2246
Epoch 3/100
13/13 [==============================] - 0s 1ms/step - loss: 773.5613
Epoch 4/100
13/13 [==============================] - 0s 1ms/step - loss: 374.1763
Epoch 5/100
13/13 [==============================] - 0s 1ms/step - loss: 381.2231
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 339.9774
Epoch 7/100
13/13 [==============================] - 0s 1ms/step - loss: 302.2349
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 275.1102
Epoch 9/100
13/13 [==============================] - 0s 1ms/step - loss: 255.5471
Epoch 10/100
13/13 [==============================] - 0s 2ms/step - loss: 231.3329
Epoch 11/100
13/13 [==============================] - 0s 2ms/step - loss: 219.7696
Epoch 12/100
13/13 [==============================] - 0s 2ms/step - loss: 208.7131
Epoch 13

In [47]:
Controlling the Amount of Output
One line is produced for each training epoch. You can eliminate this output by setting the verbose setting of the fit command:

verbose=0 - No progress output (use with Juputer if you do not want output)
verbose=1 - Display progress bar, does not work well with Jupyter
verbose=2 - Summary progress output (use with Jupyter if you want to know the loss at each epoch)

SyntaxError: ignored

In [51]:
pred = mymodel.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: (398, 1)
[[23.707472]
 [25.076267]
 [23.31501 ]
 [23.378265]
 [23.417955]
 [29.476723]
 [29.594769]
 [29.335264]
 [30.136753]
 [26.145416]]


In [54]:
We would like to see how good these predictions are. We know what the correct MPG is for each car, so we can measure how close the neural network was.

SyntaxError: ignored

In [69]:
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 13.358812495721514


In [71]:
# Sample predictions
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, " 
          + f"predicted MPG: {pred[i]}")

1. Car name: chevrolet chevelle malibu, MPG: [18.], predicted MPG: [23.707472]
2. Car name: buick skylark 320, MPG: [15.], predicted MPG: [25.076267]
3. Car name: plymouth satellite, MPG: [18.], predicted MPG: [23.31501]
4. Car name: amc rebel sst, MPG: [16.], predicted MPG: [23.378265]
5. Car name: ford torino, MPG: [17.], predicted MPG: [23.417955]
6. Car name: ford galaxie 500, MPG: [15.], predicted MPG: [29.476723]
7. Car name: chevrolet impala, MPG: [14.], predicted MPG: [29.594769]
8. Car name: plymouth fury iii, MPG: [14.], predicted MPG: [29.335264]
9. Car name: pontiac catalina, MPG: [14.], predicted MPG: [30.136753]
10. Car name: amc ambassador dpl, MPG: [15.], predicted MPG: [26.145416]


In [0]:
## Simple TensorFlow Classification: Iris

import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values


In [79]:
# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
5/5 - 0s - loss: 1.1652
Epoch 2/100
5/5 - 0s - loss: 0.9519
Epoch 3/100
5/5 - 0s - loss: 0.8911
Epoch 4/100
5/5 - 0s - loss: 0.8576
Epoch 5/100
5/5 - 0s - loss: 0.8267
Epoch 6/100
5/5 - 0s - loss: 0.8000
Epoch 7/100
5/5 - 0s - loss: 0.7670
Epoch 8/100
5/5 - 0s - loss: 0.7410
Epoch 9/100
5/5 - 0s - loss: 0.7154
Epoch 10/100
5/5 - 0s - loss: 0.6960
Epoch 11/100
5/5 - 0s - loss: 0.6656
Epoch 12/100
5/5 - 0s - loss: 0.6398
Epoch 13/100
5/5 - 0s - loss: 0.6245
Epoch 14/100
5/5 - 0s - loss: 0.5925
Epoch 15/100
5/5 - 0s - loss: 0.5682
Epoch 16/100
5/5 - 0s - loss: 0.5491
Epoch 17/100
5/5 - 0s - loss: 0.5285
Epoch 18/100
5/5 - 0s - loss: 0.5163
Epoch 19/100
5/5 - 0s - loss: 0.4968
Epoch 20/100
5/5 - 0s - loss: 0.4826
Epoch 21/100
5/5 - 0s - loss: 0.4661
Epoch 22/100
5/5 - 0s - loss: 0.4560
Epoch 23/100
5/5 - 0s - loss: 0.4321
Epoch 24/100
5/5 - 0s - loss: 0.4172
Epoch 25/100
5/5 - 0s - loss: 0.4123
Epoch 26/100
5/5 - 0s - loss: 0.3988
Epoch 27/100
5/5 - 0s - loss: 0.3867
Epoch 28/1

In [80]:
# Print out number of species found:

print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [81]:
pred = model.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: (150, 3)
[[9.96951938e-01 3.04752053e-03 5.03024296e-07]
 [9.87803698e-01 1.21936183e-02 2.74413424e-06]
 [9.94865000e-01 5.13349427e-03 1.52783900e-06]
 [9.91327465e-01 8.66907276e-03 3.40549968e-06]
 [9.97881711e-01 2.11786921e-03 4.13901006e-07]
 [9.97808754e-01 2.19086674e-03 3.64135047e-07]
 [9.96516109e-01 3.48235318e-03 1.52564758e-06]
 [9.95526850e-01 4.47221473e-03 9.19154445e-07]
 [9.87828970e-01 1.21648405e-02 6.22018160e-06]
 [9.90911961e-01 9.08618420e-03 1.86287969e-06]]


In [0]:
# If you would like to turn of scientific notation, the following 
# line can be used:
np.set_printoptions(suppress=True)

In [85]:
# The to_xy function represented the input in the same way.  
# Each row has only 1.0 value because each row is only one type
# of iris.  This is the training data, we KNOW what type of iris it 
# is.  This is called one-hot encoding.  Only one value
# is 1.0 (hot)
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [86]:

# Usually the column (pred) with the highest prediction is considered 
# to be the prediction of the neural network.  It is easy
# to convert the predictions to the expected iris species.  The argmax 
# function finds the index of the maximum prediction
# for each row.
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [99]:
# Of course it is very easy to turn these indexes back into iris species.  
# We just use the species list that we created earlier.
print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [100]:
from sklearn.metrics import accuracy_score
# Accuracy might be a more easily understood error metric.  It is 
# essentially a test score.  For all of the iris predictions,
# what percent were correct?  The downside is it does not consider 
# how confident the neural network was in each prediction.
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.98


In [101]:
# ad hoc prediction
sample_flower = np.array( [[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00420326 0.27269703 0.72309977]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica


In [102]:
# predict two sample flowers
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} are: {species[pred]}")

[[0.00420326 0.27269703 0.72309977]
 [0.9908535  0.00914295 0.00000359]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object')


In [0]:
## Part 3.3: Saving and Loading a Keras Neural Network

In [111]:
YAML - Stores the neural network structure (no weights) in the YAML file format.
JSON - Stores the neural network structure (no weights) in the JSON file format.
HDF5 - Stores the complete neural network (with weights) in the HDF5 file format. Do not confuse HDF5 with HDFS. They are different. We do not use HDFS in this class.

SyntaxError: ignored

In [112]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

save_path = "."

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

# Predict
pred = model.predict(x)

# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Before save score (RMSE): {score}")


Epoch 1/100
13/13 - 0s - loss: 611318.3125
Epoch 2/100
13/13 - 0s - loss: 254016.8906
Epoch 3/100
13/13 - 0s - loss: 73524.7656
Epoch 4/100
13/13 - 0s - loss: 10914.5400
Epoch 5/100
13/13 - 0s - loss: 409.2942
Epoch 6/100
13/13 - 0s - loss: 713.1504
Epoch 7/100
13/13 - 0s - loss: 422.2583
Epoch 8/100
13/13 - 0s - loss: 118.2442
Epoch 9/100
13/13 - 0s - loss: 87.0941
Epoch 10/100
13/13 - 0s - loss: 85.6902
Epoch 11/100
13/13 - 0s - loss: 78.7966
Epoch 12/100
13/13 - 0s - loss: 79.6307
Epoch 13/100
13/13 - 0s - loss: 75.5242
Epoch 14/100
13/13 - 0s - loss: 75.4364
Epoch 15/100
13/13 - 0s - loss: 75.5056
Epoch 16/100
13/13 - 0s - loss: 74.0201
Epoch 17/100
13/13 - 0s - loss: 73.6731
Epoch 18/100
13/13 - 0s - loss: 73.7420
Epoch 19/100
13/13 - 0s - loss: 73.7782
Epoch 20/100
13/13 - 0s - loss: 71.9966
Epoch 21/100
13/13 - 0s - loss: 74.5107
Epoch 22/100
13/13 - 0s - loss: 70.6797
Epoch 23/100
13/13 - 0s - loss: 73.1980
Epoch 24/100
13/13 - 0s - loss: 72.1769
Epoch 25/100
13/13 - 0s - loss:

In [0]:
# save neural network structure to JSON (no weights)

save_path = "."

model_json = mymodel.to_json()
with open(os.path.join(save_path,"network.json"), "w") as json_file:
    json_file.write(model_json)

# save neural network structure to YAML (no weights)
model_yaml = mymodel.to_yaml()
with open(os.path.join(save_path,"network.yaml"), "w") as yaml_file:
    yaml_file.write(model_yaml)

# save entire network to HDF5 (save everything, suggested)
mymodel.save(os.path.join(save_path,"network.h5"))




In [0]:
## Now we reload the network and perform another prediction. The RMSE should match the previous one exactly if the neural network was really saved and reloaded.

In [114]:
from tensorflow.keras.models import load_model
model2 = load_model(os.path.join(save_path,"network.h5"))
pred = model2.predict(x)
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"After load score (RMSE): {score}")

After load score (RMSE): 13.358812495721514


In [0]:
# Part 3.4: Early Stopping in Keras to Prevent Overfitting

In [0]:
import io
import requests
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values

# Split into validation and training sets
x_train, x_test, y_train, y_test = train_test_split(    
    x, y, test_size=0.25, random_state=42)

# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output
model.compile(loss='categorical_crossentropy', optimizer='adam')

In [122]:
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, 
        verbose=1, mode='auto', restore_best_weights=True)
model.fit(x_train,y_train,validation_data=(x_test,y_test),
        callbacks=[monitor],verbose=1,epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0827 - val_loss: 0.0540
Epoch 2/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0779 - val_loss: 0.0574
Epoch 3/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0781 - val_loss: 0.0527
Epoch 4/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0793 - val_loss: 0.0520
Epoch 5/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0955 - val_loss: 0.0510
Epoch 6/1000
4/4 [==============================] - 0s 9ms/step - loss: 0.0821 - val_loss: 0.0553
Epoch 7/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0841 - val_loss: 0.0602
Epoch 8/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0820 - val_loss: 0.0498
Epoch 9/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0767 - val_loss: 0.0491
Epoch 10/1000
4/4 [==============================] - 0s 50ms/step - loss: 0.0908 - val_loss: 0.0522
Epoch 11/1

In [124]:
There are a number of parameters that are specified to the EarlyStopping object.

min_delta This value should be kept small. It simply means the minimum change in error to be registered as an improvement. Setting it even smaller will not likely have a great deal of impact.
patience How long should the training wait for the validation error to improve?
verbose How much progress information do you want?
mode In general, always set this to "auto". This allows you to specify if the error should be minimized or maximized. Consider accuracy, where higher numbers are desired vs log-loss/RMSE where lower numbers are desired.
restore_best_weights This should always be set to true. This restores the weights to the values they were at when the validation set is the highest. Unless you are manually tracking the weights yourself (we do not use this technique in this course), you should have Keras perform this step for you.
As you can see from above, the entire number of requested epochs were not used. The neural network training stopped once the validation set no longer improved.

SyntaxError: ignored

In [125]:
from sklearn.metrics import accuracy_score

pred = model.predict(x_test)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y_test,axis=1)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.9736842105263158


In [126]:
## Early Stopping with Regression
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Split into validation and training sets
x_train, x_test, y_train, y_test = train_test_split(    
    x, y, test_size=0.25, random_state=42)

# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')

monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, 
        patience=5, verbose=1, mode='auto',
        restore_best_weights=True)
model.fit(x_train,y_train,validation_data=(x_test,y_test),
        callbacks=[monitor], verbose=2,epochs=1000)

Epoch 1/1000
10/10 - 0s - loss: 19868.8066 - val_loss: 809.3716
Epoch 2/1000
10/10 - 0s - loss: 2393.6631 - val_loss: 4335.1992
Epoch 3/1000
10/10 - 0s - loss: 2310.3879 - val_loss: 576.1735
Epoch 4/1000
10/10 - 0s - loss: 822.4606 - val_loss: 938.7767
Epoch 5/1000
10/10 - 0s - loss: 679.5529 - val_loss: 430.1645
Epoch 6/1000
10/10 - 0s - loss: 441.7359 - val_loss: 414.9118
Epoch 7/1000
10/10 - 0s - loss: 421.7202 - val_loss: 400.1056
Epoch 8/1000
10/10 - 0s - loss: 416.5208 - val_loss: 392.1399
Epoch 9/1000
10/10 - 0s - loss: 399.3857 - val_loss: 375.2391
Epoch 10/1000
10/10 - 0s - loss: 376.6493 - val_loss: 362.7425
Epoch 11/1000
10/10 - 0s - loss: 369.5479 - val_loss: 353.9958
Epoch 12/1000
10/10 - 0s - loss: 373.4594 - val_loss: 339.8678
Epoch 13/1000
10/10 - 0s - loss: 358.4051 - val_loss: 332.0164
Epoch 14/1000
10/10 - 0s - loss: 352.1795 - val_loss: 318.5224
Epoch 15/1000
10/10 - 0s - loss: 330.8531 - val_loss: 305.0433
Epoch 16/1000
10/10 - 0s - loss: 332.5830 - val_loss: 294.1

In [127]:
# Measure RMSE error.  RMSE is common for regression.
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred,y_test))
print(f"Final score (RMSE): {score}")

Final score (RMSE): 6.245712067609764


In [0]:
## Part 3.5: Extracting Keras Weights and Manual Neural Network Calculation

In [0]:
## Manual Neural Network Calculation

In [130]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np

# Create a dataset for the XOR function
x = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

y = np.array([
    0,
    1,
    1,
    0
])

# Build the network
# sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

done = False
cycle = 1

while not done:
    print("Cycle #{}".format(cycle))
    cycle+=1
    model = Sequential()
    model.add(Dense(2, input_dim=2, activation='relu')) 
    model.add(Dense(1)) 
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(x,y,verbose=0,epochs=10000)

    # Predict
    pred = model.predict(x)
    
    # Check if successful.  It takes several runs with this 
    # small of a network
    done = pred[0]<0.01 and pred[3]<0.01 and pred[1] > 0.9 
        and pred[2] > 0.9 
    print(pred)

IndentationError: ignored

In [131]:
pred[3]


array([16.277758], dtype=float32)

In [135]:
model.layers.count

<function list.count>

In [137]:
# Dump weights
for layerNum, layer in enumerate(model.layers):
    weights = layer.get_weights()[0]
    biases = layer.get_weights()[1]
   
    for toNeuronNum, bias in enumerate(biases):
        print(f'{layerNum}B -> L{layerNum+1}N{toNeuronNum}: {bias}')
    
    for fromNeuronNum, wgt in enumerate(weights):
        for toNeuronNum, wgt2 in enumerate(wgt):
            print(f'L{layerNum}N{fromNeuronNum} \
                  -> L{layerNum+1}N{toNeuronNum} = {wgt2}')

0B -> L1N0: -0.2351851463317871
0B -> L1N1: 0.0
0B -> L1N2: 0.0
0B -> L1N3: 0.0
0B -> L1N4: 0.0
0B -> L1N5: 0.0
0B -> L1N6: -0.14134375751018524
0B -> L1N7: 0.4202514886856079
0B -> L1N8: 0.0
0B -> L1N9: 0.0
0B -> L1N10: 0.0595504567027092
0B -> L1N11: 0.10451910644769669
0B -> L1N12: 0.0
0B -> L1N13: 0.0
0B -> L1N14: -0.09297453612089157
0B -> L1N15: 0.0
0B -> L1N16: 0.2188505381345749
0B -> L1N17: 0.0
0B -> L1N18: 0.04406147822737694
0B -> L1N19: 0.0
0B -> L1N20: 0.19929097592830658
0B -> L1N21: -0.044772859662771225
0B -> L1N22: 0.0
0B -> L1N23: 0.10987051576375961
0B -> L1N24: 0.0
L0N0                   -> L1N0 = -0.019393129274249077
L0N0                   -> L1N1 = 0.3180391490459442
L0N0                   -> L1N2 = -0.044329285621643066
L0N0                   -> L1N3 = 0.24383041262626648
L0N0                   -> L1N4 = 0.3136233985424042
L0N0                   -> L1N5 = -0.2881394624710083
L0N0                   -> L1N6 = 0.15407685935497284
L0N0                   -> L1N7 = 0.

In [133]:
input0 = 0
input1 = 1

hidden0Sum = (input0*1.3)+(input1*1.3)+(-1.3)
hidden1Sum = (input0*1.2)+(input1*1.2)+(0)

print(hidden0Sum) # 0
print(hidden1Sum) # 1.2

hidden0 = max(0,hidden0Sum)
hidden1 = max(0,hidden1Sum)

print(hidden0) # 0
print(hidden1) # 1.2

outputSum = (hidden0*-1.6)+(hidden1*0.8)+(0)
print(outputSum) # 0.96

output = max(0,outputSum)

print(output) # 0.96

0.0
1.2
0
1.2
0.96
0.96
